name: Gianluca Della Vedova

theme: minima

author:
  name: Gianluca Della Vedova
  email: gianluca@dellavedova.org

# Top menu
header_pages:
  - index.md
#  - [didattica](https://www.unimib.it/gianluca-della-vedova)
  - software.md
  - credits.md
