theme: minima

author:
  name: Gianluca Della Vedova
  email: gianluca@dellavedova.org

minima:
  social_links:
    twitter: giandellavedova
    github: gdv
    stackoverflow: "11111"
    telegram: jekyll
    keybase: jekyll

    mastodon:
     - username: jekyll
       instance: example.com
