# Permalinks
permalink:        pretty

# Setup
title:            Gianluca Della Vedova
tagline:          ''
description:      ''
url:              https://gdv.github.io
#url:              https://gianluca.dellavedova.org
baseurl:          "/"
remote_theme: "mmistakes/minimal-mistakes@4.19.1"
# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

plugins:
  - jekyll-seo-tag
  - jekyll-include-cache
