name: Gianluca Della Vedova

theme: minima

author:
  name: Gianluca Della Vedova
#  email: gianluca@dellavedova.org

# Top menu
header_pages:
  - index.md
  - didattica.md
  - software.md
  - credits.md
