title: Gianluca Della Vedova

theme: minima

#author:
#  name: Gianluca Della Vedova
#  email: gianluca@dellavedova.org

#title: Your awesome title
author:
  name: GitHub User
  email: your-email@domain.com

# Top menu
header_pages:
  - index.md
  - didattica.md
  - software.md
  - credits.md
